version: '3'

services:

  wordpress:
    image: wordpress
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_PASSWORD: wp-mysql-password

  mysql:
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wp-mysql-password


